// Two-player WebRTC data connection. Signaling is exchanged by the players.
const PROTOCOL=1,MAX_MESSAGE=8*1024*1024;
export function encodeInvitation(description){return 'BC1.'+btoa(unescape(encodeURIComponent(JSON.stringify({v:PROTOCOL,type:description.type,sdp:description.sdp}))));}
export function decodeInvitation(text,type){
 let input=String(text).trim();try{const url=new URL(input);input=new URLSearchParams(url.hash.slice(1)).get('friend')||input;}catch{}
 const match=input.match(/BC1\.([A-Za-z0-9+/=]+)/);if(!match||match[1].length>40000)throw Error('接続コードを確認してください。');
 let value;try{value=JSON.parse(decodeURIComponent(escape(atob(match[1]))));}catch{throw Error('接続コードを読み取れません。');}
 if(value.v!==PROTOCOL||value.type!==type||typeof value.sdp!=='string'||value.sdp.length>28000||!value.sdp.startsWith('v=0'))throw Error(type==='offer'?'招待リンク／招待コードを貼ってください。':'友達から届いた返信コードを貼ってください。');
 return{type:value.type,sdp:value.sdp};
}
export class FriendConnection{
 constructor({message,state}={}){this.message=message;this.state=state;this.role='solo';this.pc=null;this.channel=null;this.serial=0;this.queue=[];this.incoming=null;this.pumpTimer=null;this.generation=0;}
 connected(){return this.channel?.readyState==='open';}
 status(text){this.state?.(text);}
 close(){this.generation++;clearTimeout(this.pumpTimer);this.pumpTimer=null;this.queue=[];this.incoming=null;const pc=this.pc;this.pc=null;this.channel=null;this.role='solo';if(pc){pc.onconnectionstatechange=null;pc.close();}this.status('ひとりで冒険中');}
 setup(role){this.close();if(!globalThis.RTCPeerConnection)throw Error('このブラウザでは友達との接続を利用できません。');this.role=role;this.pc=new RTCPeerConnection({iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun.cloudflare.com:3478']}]});const pc=this.pc;pc.ondatachannel=e=>this.attach(e.channel);pc.onconnectionstatechange=()=>{if(this.pc!==pc)return;const status=pc.connectionState;if(status==='failed'){this.close();this.status('接続できませんでした。回線を変えて新しい招待でお試しください。');}else if(status==='closed')this.close();else if(status==='connected')this.status('接続しました');else if(status==='disconnected')this.status('接続を確認中…');};return pc;}
 attach(channel){this.channel=channel;channel.bufferedAmountLowThreshold=65536;channel.onbufferedamountlow=()=>this.pump();channel.onopen=()=>{this.status('接続しました');this.message?.({type:'connected'});this.pump();};channel.onclose=()=>{if(this.channel===channel)this.close();};channel.onerror=()=>this.status('接続に失敗しました。接続を終了して、もう一度お試しください。');channel.onmessage=e=>{try{this.receive(e.data);}catch{this.status('受信データに問題があるため接続を終了します。');this.close();}};}
 receive(raw){if(typeof raw!=='string'||raw.length>20000)throw Error('Frame size');const frame=JSON.parse(raw);if(frame.f!==1||!Number.isInteger(frame.id)||!Number.isInteger(frame.n)||frame.n<1||frame.n>1100||!Number.isInteger(frame.i)||typeof frame.data!=='string'||frame.data.length>8000)throw Error('Frame');if(frame.i===0){if(this.incoming)throw Error('Interleaved frame');this.incoming={id:frame.id,n:frame.n,at:0,size:0,parts:[]};}const item=this.incoming;if(!item||item.id!==frame.id||item.n!==frame.n||frame.i!==item.at)throw Error('Sequence');item.parts.push(frame.data);item.at++;item.size+=frame.data.length;if(item.size>MAX_MESSAGE)throw Error('Message size');if(item.at===item.n){this.incoming=null;const value=JSON.parse(item.parts.join(''));if(!value||typeof value.type!=='string')throw Error('Message');this.message?.(value);}}
 send(value){if(!this.connected())return false;const data=JSON.stringify(value);if(data.length>MAX_MESSAGE){this.close();this.status('世界の変更量が大きすぎるため接続を終了しました。');return false;}if(this.queue.length>1200)return false;const id=++this.serial,n=Math.max(1,Math.ceil(data.length/8000));for(let i=0;i<n;i++)this.queue.push(JSON.stringify({f:1,id,n,i,data:data.slice(i*8000,(i+1)*8000)}));this.pump();return true;}
 pump(){clearTimeout(this.pumpTimer);this.pumpTimer=null;if(!this.connected())return;while(this.queue.length&&this.channel.bufferedAmount<131072){try{this.channel.send(this.queue.shift());}catch{this.close();return;}}if(this.queue.length)this.pumpTimer=setTimeout(()=>this.pump(),30);}
 async gathered(pc){if(pc.iceGatheringState==='complete')return;await new Promise(resolve=>{const finish=()=>{clearTimeout(timer);pc.removeEventListener('icegatheringstatechange',check);resolve();};const check=()=>{if(pc.iceGatheringState==='complete')finish();};const timer=setTimeout(finish,8500);pc.addEventListener('icegatheringstatechange',check);});if(this.pc!==pc)throw Error('接続をキャンセルしました。');}
 async invite(){const pc=this.setup('host');this.status('招待リンクを作成中…');this.attach(pc.createDataChannel('block-coaster',{ordered:true}));await pc.setLocalDescription(await pc.createOffer());await this.gathered(pc);if(!pc.localDescription.sdp.includes('a=candidate:')){this.close();throw Error('接続経路が見つかりません。別の回線やWebRTC対応ブラウザでお試しください。');}this.status('友達の返信コードを待っています');return encodeInvitation(pc.localDescription);}
 async join(text){const offer=decodeInvitation(text,'offer'),pc=this.setup('guest');this.status('返信コードを作成中…');await pc.setRemoteDescription(offer);await pc.setLocalDescription(await pc.createAnswer());await this.gathered(pc);if(!pc.localDescription.sdp.includes('a=candidate:')){this.close();throw Error('接続経路が見つかりません。別の回線やWebRTC対応ブラウザでお試しください。');}this.status('返信コードを友達に送ってください');return encodeInvitation(pc.localDescription);}
 async accept(text){if(this.role!=='host'||!this.pc)throw Error('先に招待リンクを作ってください。');await this.pc.setRemoteDescription(decodeInvitation(text,'answer'));this.status('友達につないでいます…');}
}
export function cleanFriendPose(value){
 if(!value||!Array.isArray(value.position)||value.position.length!==3||!value.position.every(v=>Number.isFinite(v)&&Math.abs(v)<=1e7)||!Number.isFinite(value.yaw)||!Number.isFinite(value.pitch)||Math.abs(value.pitch)>1.5)return null;
 return{position:[...value.position],yaw:value.yaw,pitch:value.pitch,name:String(value.name||'旅人').replace(/[\x00-\x1f\x7f]/g,'').slice(0,16),mode:value.mode==='ride'?'ride':'build',creative:!!value.creative};
}
export function createFriendAvatar(THREE,scene){
 const root=new THREE.Group();scene.add(root);root.visible=false;const geometry=new THREE.BoxGeometry(1,1,1),materials={skin:new THREE.MeshLambertMaterial({color:0xdca779}),shirt:new THREE.MeshLambertMaterial({color:0x62b2c4}),pants:new THREE.MeshLambertMaterial({color:0x42538f}),hair:new THREE.MeshLambertMaterial({color:0x513c2d}),eyes:new THREE.MeshLambertMaterial({color:0x263331})},limbs=[];
 const part=(key,x,y,z,sx,sy,sz)=>{const mesh=new THREE.Mesh(geometry,materials[key]);mesh.position.set(x,y,z);mesh.scale.set(sx,sy,sz);root.add(mesh);return mesh;};
 part('shirt',0,1,0,.52,.64,.28);const head=new THREE.Group();head.position.y=1.52;root.add(head);const face=new THREE.Mesh(geometry,materials.skin);face.scale.set(.48,.48,.48);head.add(face);const hair=new THREE.Mesh(geometry,materials.hair);hair.position.set(0,.19,.01);hair.scale.set(.49,.13,.49);head.add(hair);for(const x of[-.12,.12]){const eye=new THREE.Mesh(geometry,materials.eyes);eye.position.set(x,.02,-.246);eye.scale.set(.06,.06,.015);head.add(eye);}for(const x of[-.34,.34])limbs.push(part('skin',x,1,0,.16,.64,.2));for(const x of[-.14,.14])limbs.push(part('pants',x,.36,0,.23,.72,.26));
 const canvas=document.createElement('canvas');canvas.width=256;canvas.height=48;const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const label=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,depthWrite:false}));label.position.y=2.15;label.scale.set(2.7,.5,1);root.add(label);let currentName='',pose=null,lastPosition=null,phase=0;
 return{set(value){pose=value;if(!value){root.visible=false;lastPosition=null;return;}root.visible=true;if(currentName!==value.name){currentName=value.name;const g=canvas.getContext('2d');g.clearRect(0,0,256,48);g.fillStyle='#15261fbb';g.fillRect(0,0,256,48);g.font='bold 24px sans-serif';g.textAlign='center';g.fillStyle='#fff';g.fillText(value.name,128,32,246);texture.needsUpdate=true;}},tick(dt){if(!pose)return;const target=new THREE.Vector3(...pose.position);if(!lastPosition){root.position.copy(target);lastPosition=target.clone();}const distance=target.distanceTo(lastPosition);phase+=distance*9;lastPosition.copy(target);root.position.lerp(target,Math.min(1,dt*14));root.rotation.y=pose.yaw;head.rotation.x=-pose.pitch;limbs.forEach((part,i)=>part.rotation.x=distance>.001?Math.sin(phase+(i===0||i===3?0:Math.PI))*.45:0);},stats:()=>({visible:root.visible,name:currentName,position:root.position.toArray()})};
}
