// Deterministic, bounded voxel streaming. All art and structures are original.
export const WORLD_MIN_Y = -64, WORLD_MAX_Y = 112, WORLD_CHUNK = 16;
export const BLOCKS = Object.freeze({ AIR:0, DIRT:1, STONE:2, GRASS:3, SNOW:4, WOOD:5, ROOF:6, RUIN:7, BEDROCK:8, LEAVES:9, PLANK:10, COBBLE:11, COAL:12, IRON:13, GOLD:14, DEEP:15, TABLE:16, FURNACE:17, CHEST:18, GLASS:19, SAND:20, GLOW:21, WATER:22, TORCH:23, DIAMOND:24, EMERALD:25, REDSTONE:26, LAPIS:27, COPPER:28, COPPER_BLOCK:29, IRON_BLOCK:30, GOLD_BLOCK:31, DIAMOND_BLOCK:32, EMERALD_BLOCK:33, OBSIDIAN:34, BRICK:35, BOOKSHELF:36, CACTUS:37, MUSHROOM:38, BASALT:39, CLAY:40, SNOW_LOG:41, PINE_LEAVES:42, JUNGLE_LOG:43, JUNGLE_LEAVES:44, RED_SAND:45, ICE:46, LAVA:47, WOOL:48 });
const WV_SIZE = 16, WV_PLANE = 256, WV_DEPTH = WORLD_MAX_Y - WORLD_MIN_Y, WV_VOLUME = WV_PLANE * WV_DEPTH, WV_REGION = 64, WV_SEA = 5;
const wvClamp = (v,a,b) => Math.max(a, Math.min(b,v));
const wvSmooth = t => t*t*(3-2*t);
const wvLerp = (a,b,t) => a+(b-a)*t;
const wvIndex = (x,y,z) => (y-WORLD_MIN_Y)*WV_PLANE+z*WV_SIZE+x;
export function hash3(x,y,z,seed=3) { let n=Math.imul(x|0,374761393)^Math.imul(y|0,668265263)^Math.imul(z|0,2147483647)^Math.imul(seed|0,1597334677);n=Math.imul(n^(n>>>13),1274126177);return ((n^(n>>>16))>>>0)/4294967296; }
export function noise2(x,z,seed=3) {const ix=Math.floor(x),iz=Math.floor(z),fx=wvSmooth(x-ix),fz=wvSmooth(z-iz);return wvLerp(wvLerp(hash3(ix,0,iz,seed),hash3(ix+1,0,iz,seed),fx),wvLerp(hash3(ix,0,iz+1,seed),hash3(ix+1,0,iz+1,seed),fx),fz);}
const WV_BIOMES = [
 {id:'plains',name:'平原',color:'#78a74b',height:13,rough:5,top:BLOCKS.GRASS,soil:BLOCKS.DIRT},
 {id:'forest',name:'森林',color:'#477837',height:18,rough:9,top:BLOCKS.GRASS,soil:BLOCKS.DIRT},
 {id:'desert',name:'砂漠',color:'#dec18a',height:14,rough:6,top:BLOCKS.SAND,soil:BLOCKS.SAND},
 {id:'taiga',name:'タイガ',color:'#567c6b',height:23,rough:13,top:BLOCKS.GRASS,soil:BLOCKS.DIRT},
 {id:'snow',name:'雪山',color:'#e9f1f5',height:54,rough:32,top:BLOCKS.SNOW,soil:BLOCKS.STONE},
 {id:'jungle',name:'ジャングル',color:'#35913e',height:23,rough:13,top:BLOCKS.GRASS,soil:BLOCKS.DIRT},
 {id:'badlands',name:'赤砂の高原',color:'#bd7349',height:31,rough:17,top:BLOCKS.RED_SAND,soil:BLOCKS.CLAY},
 {id:'ocean',name:'海岸・海',color:'#669ebb',height:-11,rough:7,top:BLOCKS.SAND,soil:BLOCKS.CLAY}
].map(b=>Object.freeze(b));

export class VoxelWorld {
 constructor({seed=3,legacy=null,maxCachedChunks=196}={}) {this.seed=seed|0;this.legacy=legacy;this.maxCachedChunks=Math.max(9,Math.floor(maxCachedChunks));this.edits=new Map();this._editsByChunk=new Map();this._chunks=new Map();this._regions=new Map();this._generated=0;this._clock=0;}
 _inLegacy(x,z) {return !!this.legacy&&x>=0&&z>=0&&x<64&&z<64;}
 _legacyVoxel(x,y,z) {const l=this.legacy;return y>=l.minY&&y<l.maxY?l.data[(y-l.minY)*4096+z*64+x]:null;}
 _biomeCells(x,z) {const cx=Math.floor(x/128),cz=Math.floor(z/128),cells=[];for(let oz=-1;oz<=1;oz++)for(let ox=-1;ox<=1;ox++){const a=cx+ox,b=cz+oz,px=(a+.5)*128+(hash3(a,101,b,this.seed)-.5)*38,pz=(b+.5)*128+(hash3(a,102,b,this.seed)-.5)*38;const k=Math.floor(hash3(a,104,b,this.seed)*8),d=(px-x)**2+(pz-z)**2;cells.push({d,biome:WV_BIOMES[k]});}cells.sort((a,b)=>a.d-b.d);return cells;}
 biome(x,z) {if(this._inLegacy(x,z))return this.legacy.heights[Math.floor(z)*64+Math.floor(x)]>=35?WV_BIOMES[4]:WV_BIOMES[0];return this._biomeCells(x,z)[0].biome;}
 _height(x,z) {if(this._inLegacy(x,z))return this.legacy.heights[z*64+x];const cells=this._biomeCells(x,z);let sum=0,base=0,rough=0;for(const c of cells){const w=Math.exp(-(c.d-cells[0].d)/5900);sum+=w;base+=c.biome.height*w;rough+=c.biome.rough*w;}base/=sum;rough/=sum;let h=base+(noise2(x/82,z/82,this.seed+11)-.5)*rough*2+(noise2(x/27,z/27,this.seed+19)-.5)*rough*.63+(noise2(x/9,z/9,this.seed+29)-.5)*2.2;
  if(this.legacy){const ex=wvClamp(x,0,63),ez=wvClamp(z,0,63),dist=Math.hypot(x-ex,z-ez);if(dist<48)h=wvLerp(this.legacy.heights[ez*64+ex],h,wvSmooth(dist/48));}
  return wvClamp(Math.floor(h),-15,96);
 }
 height(x,z) {x=Math.floor(x);z=Math.floor(z);const cx=Math.floor(x/16),cz=Math.floor(z/16),c=this.chunk(cx,cz);return c.heights[(z-cz*16)*16+x-cx*16];}
 _region(rx,rz) {const key=rx+','+rz;if(this._regions.has(key)){const value=this._regions.get(key);this._regions.delete(key);this._regions.set(key,value);return value;}const s=this.seed,rnd=(salt)=>hash3(rx,salt,rz,s),node=(a,b)=>({x:a*64+26+hash3(a,301,b,s)*12,z:b*64+26+hash3(a,302,b,s)*12,y:-20-hash3(a,303,b,s)*27}),n=node(rx,rz),spheres=[],structures=[];
  const sphere=(x,y,z,rx0,ry,rz0)=>spheres.push({x,y,z,rx:rx0,ry,rz:rz0});
  const path=(a,b,radius,salt)=>{const len=Math.hypot(b.x-a.x,b.y-a.y,b.z-a.z),steps=Math.ceil(len/2.7),phase=rnd(salt)*6.28;for(let i=0;i<=steps;i++){const t=i/steps,curve=Math.sin(t*Math.PI);const p={x:wvLerp(a.x,b.x,t)+Math.sin(t*7+phase)*curve*5,y:wvLerp(a.y,b.y,t)+Math.sin(t*8+phase)*curve*3,z:wvLerp(a.z,b.z,t)+Math.cos(t*6+phase)*curve*5},r=radius*(.88+.22*Math.sin(t*13+phase));sphere(p.x,p.y,p.z,r,r*.83,r);}};
  path(n,node(rx+1,rz),2.6+rnd(304)*1.1,305);path(n,node(rx,rz+1),2.5+rnd(306),307);
  sphere(n.x,n.y,n.z,7+rnd(308)*7,5+rnd(309)*5,7+rnd(310)*7);
  const deep={x:rx*64+8+rnd(311)*48,z:rz*64+8+rnd(312)*48,y:-48-rnd(313)*7};path(n,deep,2.2+rnd(314),315);sphere(deep.x,deep.y,deep.z,4+rnd(316)*4,3.4,5+rnd(317)*4);
  for(let i=0;i<2;i++){const branch={x:rx*64+rnd(320+i*5)*64,z:rz*64+rnd(321+i*5)*64,y:-8-rnd(322+i*5)*35};path(n,branch,2.1+rnd(323+i*5),324+i*5);sphere(branch.x,branch.y,branch.z,4+rnd(340+i)*4,3+rnd(350+i)*3,4+rnd(360+i)*4);}
  if(rnd(370)<.38){const ex=Math.floor(rx*64+10+rnd(371)*44),ez=Math.floor(rz*64+10+rnd(372)*44),surface={x:ex+.5,z:ez+.5,y:this._height(ex,ez)+1};path(n,surface,2.35,373);}
  const sx=Math.floor(rx*64+25+rnd(380)*14),sz=Math.floor(rz*64+25+rnd(381)*14),b=this.biome(sx,sz),h=this._height(sx,sz);if(rnd(382)<.43){let type=b.id==='desert'?'temple':b.id==='jungle'?'jungle_ruin':b.id==='snow'||b.id==='taiga'?'igloo':b.id==='ocean'?'shipwreck':b.id==='plains'||b.id==='forest'?'village':'watchtower';const extent=type==='village'?19:type==='temple'?9:8,surfaceY=type==='shipwreck'?Math.max(h,WV_SEA-2):h;structures.push({id:`${rx},${rz}:surface`,type,name:{temple:'砂漠の神殿',jungle_ruin:'密林の苔石遺跡',igloo:'氷雪の小屋',shipwreck:'海岸の難破船',village:'旅人の小さな村',watchtower:'山の展望塔'}[type],x:sx,z:sz,y:surfaceY,bounds:{minX:sx-extent,maxX:sx+extent,minZ:sz-extent,maxZ:sz+extent,minY:surfaceY-9,maxY:surfaceY+15}});}
  if(rnd(383)<.40)structures.push({id:`${rx},${rz}:mine`,type:'mineshaft',name:'地下の廃坑',x:Math.floor(n.x),z:Math.floor(n.z),y:Math.floor(n.y)-2,bounds:{minX:Math.floor(n.x)-13,maxX:Math.floor(n.x)+13,minZ:Math.floor(n.z)-6,maxZ:Math.floor(n.z)+6,minY:Math.floor(n.y)-4,maxY:Math.floor(n.y)+4}});
  const pools=[];if(rnd(390)<.26)pools.push({x:deep.x,z:deep.z,y:Math.floor(deep.y-1),radius:3.1,type:rnd(391)<.20?BLOCKS.LAVA:BLOCKS.WATER});
  const region={spheres,pools,structures:structures.filter(st=>!this.legacy||st.bounds.maxX<0||st.bounds.minX>63||st.bounds.maxZ<0||st.bounds.minZ>63)};this._regions.set(key,region);while(this._regions.size>144)this._regions.delete(this._regions.keys().next().value);return region;
 }
 _nearRegions(x,z,radius=32) {const regions=[];for(let rz=Math.floor((z-radius)/64);rz<=Math.floor((z+radius)/64);rz++)for(let rx=Math.floor((x-radius)/64);rx<=Math.floor((x+radius)/64);rx++)regions.push(this._region(rx,rz));return regions;}
 structuresNear(x,z,radius=100) {const list=this._nearRegions(x,z,radius+32).flatMap(r=>r.structures).filter(s=>Math.hypot(s.x-x,s.z-z)<=radius);if(this.legacy?.structures)for(const s of this.legacy.structures)if(Math.hypot(s.x-x,s.z-z)<=radius)list.push({...s,type:s.type||'legacy',id:s.id||`legacy:${s.x},${s.z}`});return list.map(s=>({...s,bounds:s.bounds?{...s.bounds}:undefined}));}
 _generate(cx,cz) {const x0=cx*16,z0=cz*16,data=new Uint8Array(WV_VOLUME),heights=new Int16Array(256),cave=new Uint8Array(WV_VOLUME),chunk={cx,cz,data,heights,cave,used:++this._clock},biomes=[];
  const write=(x,y,z,type,mark=false)=>{if(x<x0||x>=x0+16||z<z0||z>=z0+16||y<WORLD_MIN_Y||y>=WORLD_MAX_Y||this._inLegacy(x,z)&&y>=this.legacy.minY&&y<this.legacy.maxY)return;const at=wvIndex(x-x0,y,z-z0);data[at]=type;if(mark)cave[at]=1;};
  for(let z=0;z<16;z++)for(let x=0;x<16;x++){const wx=x0+x,wz=z0+z,h=this._height(wx,wz),b=this.biome(wx,wz),col=z*16+x;heights[col]=h;biomes[col]=b;for(let y=WORLD_MIN_Y;y<Math.max(h,WV_SEA);y++){let t=y===WORLD_MIN_Y?BLOCKS.BEDROCK:y>=h?b.id==='snow'&&y===WV_SEA-1?BLOCKS.ICE:BLOCKS.WATER:y===h-1?b.top:y>=h-4?b.soil:y<-15?BLOCKS.DEEP:BLOCKS.STONE;if(b.id==='badlands'&&y>=h-12&&y<h-4)t=(Math.floor(y/3)%2)?BLOCKS.CLAY:BLOCKS.RED_SAND;data[wvIndex(x,y,z)]=t;}
   if(this._inLegacy(wx,wz)){const l=this.legacy;for(let y=l.minY;y<l.maxY;y++){const at=wvIndex(x,y,z),li=(y-l.minY)*4096+wz*64+wx;data[at]=l.data[li];cave[at]=l.caveMask?.[li]||0;}}
  }
  const regions=this._nearRegions(x0+8,z0+8,78);
  for(const region of regions)for(const s of region.spheres){if(s.x+s.rx<x0||s.x-s.rx>x0+16||s.z+s.rz<z0||s.z-s.rz>z0+16)continue;const minX=Math.max(x0,Math.floor(s.x-s.rx-1)),maxX=Math.min(x0+15,Math.ceil(s.x+s.rx)),minZ=Math.max(z0,Math.floor(s.z-s.rz-1)),maxZ=Math.min(z0+15,Math.ceil(s.z+s.rz));for(let z=minZ;z<=maxZ;z++)for(let x=minX;x<=maxX;x++){const d=((x+.5-s.x)/s.rx)**2+((z+.5-s.z)/s.rz)**2;if(d>1.12)continue;const wobble=(hash3(Math.floor(x/2),Math.floor(s.y/4),Math.floor(z/2),this.seed+403)-.5)*.2;const yr=s.ry*Math.sqrt(Math.max(0,1.04+wobble-d)),lo=Math.max(-61,Math.ceil(s.y-yr-.5)),hi=Math.min(WORLD_MAX_Y-1,Math.floor(s.y+yr-.5));for(let y=lo;y<=hi;y++){const at=wvIndex(x-x0,y,z-z0),t=data[at];if(t!==BLOCKS.BEDROCK&&t!==BLOCKS.WATER&&t!==BLOCKS.ICE)write(x,y,z,BLOCKS.AIR,true);}}}
  for(const region of regions)for(const p of region.pools)for(let z=Math.max(z0,Math.floor(p.z-p.radius));z<=Math.min(z0+15,Math.ceil(p.z+p.radius));z++)for(let x=Math.max(x0,Math.floor(p.x-p.radius));x<=Math.min(x0+15,Math.ceil(p.x+p.radius));x++)if((x+.5-p.x)**2+(z+.5-p.z)**2<p.radius**2)for(let y=p.y-3;y<=p.y;y++){const at=wvIndex(x-x0,y,z-z0);if(data[at]===BLOCKS.AIR&&cave[at])write(x,y,z,p.type);else if(p.type===BLOCKS.LAVA&&y===p.y-3&&data[at]===BLOCKS.DEEP)write(x,y,z,BLOCKS.OBSIDIAN);}
  this._ores(chunk,write,biomes);
  this._trees(chunk,write);
  for(const region of regions)for(const s of region.structures)if(s.bounds.maxX>=x0&&s.bounds.minX<x0+16&&s.bounds.maxZ>=z0&&s.bounds.minZ<z0+16)this._structure(chunk,s,write);
  chunk.baseData=data.slice();
  const localEdits=this._editsByChunk.get(cx+','+cz);if(localEdits)for(const [key,type]of localEdits){const p=key.split(',').map(Number);data[wvIndex(p[0]-x0,p[1],p[2]-z0)]=type;}
  this._generated++;return chunk;
 }
 _ores(chunk,write,biomes) {const x0=chunk.cx*16,z0=chunk.cz*16;for(let gz=Math.floor((z0-3)/6);gz<=Math.floor((z0+18)/6);gz++)for(let gx=Math.floor((x0-3)/6);gx<=Math.floor((x0+18)/6);gx++)for(let gy=-10;gy<=15;gy++){if(hash3(gx,gy,gz,this.seed+420)>.76)continue;const x=gx*6+Math.floor(hash3(gx,gy,gz,this.seed+421)*6),y=gy*6+Math.floor(hash3(gx,gy,gz,this.seed+422)*6),z=gz*6+Math.floor(hash3(gx,gy,gz,this.seed+423)*6),roll=hash3(gx,gy,gz,this.seed+424),b=this.biome(x,z);let type;
   if(y<-36)type=roll<.12?BLOCKS.DIAMOND:roll<.28?BLOCKS.REDSTONE:roll<.42?BLOCKS.LAPIS:roll<.60?BLOCKS.GOLD:roll<.75?BLOCKS.IRON:roll<.88?BLOCKS.COAL:BLOCKS.EMERALD;
   else if(y<-8)type=roll<.07?BLOCKS.EMERALD:roll<.24?BLOCKS.GOLD:roll<.36?BLOCKS.LAPIS:roll<.45?BLOCKS.REDSTONE:roll<.72?BLOCKS.IRON:roll<.89?BLOCKS.COAL:BLOCKS.COPPER;
   else type=roll<.36?BLOCKS.COAL:roll<.68?BLOCKS.IRON:roll<.93?BLOCKS.COPPER:b.id==='badlands'?BLOCKS.GOLD:b.id==='snow'?BLOCKS.EMERALD:BLOCKS.COAL;
   const rx=1.5+hash3(gx,gy,gz,this.seed+425)*1.4,ry=1+hash3(gx,gy,gz,this.seed+426)*1.4,rz=1.5+hash3(gx,gy,gz,this.seed+427)*1.4;for(let dz=-3;dz<=3;dz++)for(let dx=-3;dx<=3;dx++)for(let dy=-2;dy<=2;dy++){const wx=x+dx,wy=y+dy,wz=z+dz;if(wx<x0||wx>=x0+16||wz<z0||wz>=z0+16||wy<=WORLD_MIN_Y||wy>=WORLD_MAX_Y||(dx/rx)**2+(dy/ry)**2+(dz/rz)**2>1)continue;const at=wvIndex(wx-x0,wy,wz-z0);if(chunk.data[at]===BLOCKS.STONE||chunk.data[at]===BLOCKS.DEEP)write(wx,wy,wz,type);}
  }
 }
 _trees(chunk,write) {const x0=chunk.cx*16,z0=chunk.cz*16;for(let gz=Math.floor((z0-6)/8);gz<=Math.floor((z0+21)/8);gz++)for(let gx=Math.floor((x0-6)/8);gx<=Math.floor((x0+21)/8);gx++){const x=gx*8+1+Math.floor(hash3(gx,450,gz,this.seed)*6),z=gz*8+1+Math.floor(hash3(gx,451,gz,this.seed)*6),h=this._height(x,z),b=this.biome(x,z),roll=hash3(gx,452,gz,this.seed);if(this._inLegacy(x,z)||h<=WV_SEA||h>84)continue;if(b.id==='desert'&&roll<.25){for(let y=h;y<h+2+Math.floor(roll*8);y++)write(x,y,z,BLOCKS.CACTUS);continue;}if(b.id==='badlands'||b.id==='ocean'||b.id==='snow'&&h>60)continue;const density=b.id==='jungle'?.87:b.id==='forest'?.76:b.id==='taiga'?.62:b.id==='snow'?.26:.16;if(roll>density)continue;const pine=b.id==='snow'||b.id==='taiga',jungle=b.id==='jungle',trunk=pine?BLOCKS.SNOW_LOG:jungle?BLOCKS.JUNGLE_LOG:BLOCKS.WOOD,leaves=pine?BLOCKS.PINE_LEAVES:jungle?BLOCKS.JUNGLE_LEAVES:BLOCKS.LEAVES,th=pine?7+Math.floor(roll*5):jungle?8+Math.floor(roll*6):4+Math.floor(roll*4);for(let y=h;y<h+th;y++)write(x,y,z,trunk);for(let dy=-3;dy<=1;dy++){const r=pine?dy<=-2?2:1:jungle?3:2;for(let dz=-r;dz<=r;dz++)for(let dx=-r;dx<=r;dx++)if(Math.abs(dx)+Math.abs(dz)<=r*1.6&&!(dx===0&&dz===0&&dy<0))write(x+dx,h+th+dy,z+dz,leaves);}if(jungle&&roll<.5)for(let k=0;k<3;k++)write(x+2,h+k,z+2,BLOCKS.MUSHROOM);}
 }
 _structure(chunk,s,write) {const box=(x,y,z,sx,sy,sz,t,mark=false)=>{for(let zz=z;zz<z+sz;zz++)for(let xx=x;xx<x+sx;xx++)for(let yy=y;yy<y+sy;yy++)write(xx,yy,zz,t,mark);};const platform=(x,z,w,d,y,t)=>{for(let zz=z;zz<z+d;zz++)for(let xx=x;xx<x+w;xx++){const h=this._height(xx,zz);box(xx,Math.min(h,y)-1,zz,1,y-Math.min(h,y)+1,1,t);box(xx,y,zz,1,Math.max(13,h-y+3),1,BLOCKS.AIR);if(xx>=chunk.cx*16&&xx<chunk.cx*16+16&&zz>=chunk.cz*16&&zz<chunk.cz*16+16&&!this._inLegacy(xx,zz))chunk.heights[(zz-chunk.cz*16)*16+xx-chunk.cx*16]=y;}};
  const house=(x,z,y)=>{platform(x,z,7,7,y,BLOCKS.COBBLE);box(x,y-1,z,7,1,7,BLOCKS.PLANK);for(let dz=0;dz<7;dz++)for(let dx=0;dx<7;dx++)if(dx===0||dx===6||dz===0||dz===6){box(x+dx,y,z+dz,1,4,1,(dx===0||dx===6)&&(dz===0||dz===6)?BLOCKS.WOOD:BLOCKS.PLANK);if((dx===0||dx===6)&&dz===3)box(x+dx,y+1,z+dz,1,2,1,BLOCKS.GLASS);}box(x+3,y,z,1,3,1,BLOCKS.AIR);for(let k=0;k<4;k++)box(x-1+k,y+4+k,z-1,9-k*2,1,9,BLOCKS.ROOF);write(x+1,y,z+5,BLOCKS.CHEST);write(x+5,y,z+5,BLOCKS.TABLE);write(x+4,y,z+5,BLOCKS.FURNACE);write(x+3,y+3,z+3,BLOCKS.TORCH);};
  const x=s.x,z=s.z,y=s.y;
  if(s.type==='village'){house(x-12,z-10,y);house(x+6,z-10,y);house(x-3,z+7,y);platform(x-2,z-7,3,14,y,BLOCKS.COBBLE);platform(x-10,z-2,21,3,y,BLOCKS.COBBLE);box(x-1,y,z-1,3,1,3,BLOCKS.COBBLE);write(x,y,z,BLOCKS.WATER);box(x-8,y,z+8,3,1,6,BLOCKS.DIRT);for(let dz=0;dz<6;dz++)for(let dx=0;dx<3;dx++)write(x-8+dx,y+1,z+8+dz,BLOCKS.MUSHROOM);}
  else if(s.type==='temple'){platform(x-8,z-8,17,17,y,BLOCKS.SAND);box(x-7,y-1,z-7,15,1,15,BLOCKS.SAND);for(let k=0;k<4;k++){const r=7-k;for(let dx=-r;dx<=r;dx++)for(let dz=-r;dz<=r;dz++)if(Math.abs(dx)===r||Math.abs(dz)===r)box(x+dx,y+k,z+dz,1,1,1,(dx+dz)%3?BLOCKS.SAND:BLOCKS.CLAY);}box(x-4,y,z-4,9,5,9,BLOCKS.AIR);for(const dx of[-6,5]){box(x+dx,y,z-7,2,8,2,BLOCKS.SAND);box(x+dx,y+3,z-8,2,2,1,BLOCKS.CLAY);}box(x-1,y,z-7,3,3,4,BLOCKS.AIR);box(x-3,y-8,z-3,7,6,7,BLOCKS.AIR,true);box(x-3,y-9,z-3,7,1,7,BLOCKS.RUIN);for(let k=0;k<7;k++){box(x+2,y-k-1,z-4+k,2,1,1,BLOCKS.SAND);box(x+2,y-k,z-4+k,2,3,1,BLOCKS.AIR,true);}write(x-2,y-8,z-2,BLOCKS.CHEST);write(x+2,y-8,z+2,BLOCKS.CHEST);box(x-1,y-9,z-1,3,1,3,BLOCKS.OBSIDIAN);}
  else if(s.type==='jungle_ruin'){platform(x-6,z-6,13,13,y,BLOCKS.RUIN);for(let k=0;k<4;k++){const r=6-k;for(let dz=-r;dz<=r;dz++)for(let dx=-r;dx<=r;dx++)if(Math.abs(dx)===r||Math.abs(dz)===r)write(x+dx,y+k,z+dz,BLOCKS.RUIN);}for(const dx of[-3,3])for(const dz of[-3,3])box(x+dx,y,z+dz,1,7,1,BLOCKS.RUIN);box(x-1,y,z-6,3,3,4,BLOCKS.AIR);box(x-3,y-4,z-3,7,4,7,BLOCKS.AIR,true);box(x-3,y-5,z-3,7,1,7,BLOCKS.RUIN);for(let k=0;k<4;k++){write(x+2,y-k-1,z-3+k,BLOCKS.RUIN);box(x+2,y-k,z-3+k,1,3,1,BLOCKS.AIR,true);}write(x-2,y-4,z+2,BLOCKS.CHEST);write(x-2,y-4,z+1,BLOCKS.TABLE);box(x-5,y+2,z+5,3,2,1,BLOCKS.JUNGLE_LEAVES);}
  else if(s.type==='igloo'){platform(x-4,z-4,9,9,y,BLOCKS.SNOW);for(let dy=0;dy<5;dy++){const r=dy<3?4:dy===3?3:2;for(let dz=-r;dz<=r;dz++)for(let dx=-r;dx<=r;dx++)if(Math.abs(dx)+Math.abs(dz)<=r+2&&(Math.abs(dx)===r||Math.abs(dz)===r||dy===4))write(x+dx,y+dy,z+dz,BLOCKS.SNOW);}box(x-1,y,z-4,3,3,3,BLOCKS.AIR);write(x-2,y,z+2,BLOCKS.CHEST);write(x+2,y,z+2,BLOCKS.FURNACE);write(x+1,y,z+2,BLOCKS.TABLE);write(x+2,y+1,z+2,BLOCKS.TORCH);box(x-2,y-5,z-2,5,4,5,BLOCKS.AIR,true);box(x-2,y-6,z-2,5,1,5,BLOCKS.PLANK);write(x+1,y-5,z+1,BLOCKS.CHEST);}
  else if(s.type==='watchtower'){platform(x-3,z-3,7,7,y,BLOCKS.COBBLE);for(const dx of[-3,3])for(const dz of[-3,3])box(x+dx,y,z+dz,1,10,1,BLOCKS.WOOD);const stairs=[[-2,-2],[-1,-2],[0,-2],[1,-2],[2,-2],[2,-1],[2,0],[2,1],[2,2]];for(let k=0;k<9;k++){const [dx,dz]=stairs[k];write(x+dx,y+k,z+dz,BLOCKS.PLANK);box(x+dx,y+k+1,z+dz,1,3,1,BLOCKS.AIR);}box(x-3,y+9,z-3,7,1,7,BLOCKS.PLANK);box(x+2,y+9,z+1,1,1,1,BLOCKS.AIR);box(x-2,y+12,z-2,5,1,5,BLOCKS.ROOF);write(x-2,y+10,z+2,BLOCKS.CHEST);write(x+2,y,z+2,BLOCKS.TABLE);}
  else if(s.type==='shipwreck'){const sy=Math.max(y,WV_SEA-2);for(let k=0;k<4;k++){const r=k<2?2:3;for(let dx=-7;dx<=7;dx++)for(let dz=-r;dz<=r;dz++)if(Math.abs(dx)<7-Math.max(0,Math.abs(dz)-1)&&(k===0||Math.abs(dz)===r||Math.abs(dx)>5))write(x+dx,sy+k,z+dz,BLOCKS.PLANK);}box(x-5,sy+1,z-1,4,2,3,BLOCKS.AIR);box(x,sy+1,z,1,9,1,BLOCKS.WOOD);box(x+1,sy+6,z,4,3,1,BLOCKS.WOOL);write(x-4,sy+1,z,BLOCKS.CHEST);write(x+4,sy+1,z,BLOCKS.CHEST);}
  else if(s.type==='mineshaft'){box(x-13,y,z-2,27,4,5,BLOCKS.AIR,true);box(x-4,y,z-6,9,4,13,BLOCKS.AIR,true);box(x-13,y-1,z-2,27,1,5,BLOCKS.PLANK);box(x-4,y-1,z-6,9,1,13,BLOCKS.PLANK);for(let k=-12;k<=12;k+=6){box(x+k,y,z-2,1,3,1,BLOCKS.WOOD);box(x+k,y,z+2,1,3,1,BLOCKS.WOOD);box(x+k,y+3,z-2,1,1,5,BLOCKS.PLANK);write(x+k,y+2,z+1,BLOCKS.TORCH);}write(x-11,y,z+1,BLOCKS.CHEST);write(x+3,y,z+5,BLOCKS.CHEST);write(x+2,y,z+5,BLOCKS.TABLE);write(x+1,y,z+5,BLOCKS.FURNACE);}
 }
 lootAt(x,y,z) {x=Math.floor(x);y=Math.floor(y);z=Math.floor(z);if(this.baseVoxel(x,y,z)!==BLOCKS.CHEST)return [];const r=hash3(x,y,z,this.seed+600);return [{id:'iron',count:3+Math.floor(r*6)},{id:'coal',count:4+Math.floor(hash3(x,y,z,this.seed+601)*9)},{id:'torch',count:6+Math.floor(hash3(x,y,z,this.seed+602)*10)},{id:r<.22?'diamond':r<.48?'emerald':r<.7?'gold':'rail',count:r<.7?1+Math.floor(r*5):12},{id:hash3(x,y,z,this.seed+603)<.5?'apple':'plank',count:3+Math.floor(hash3(x,y,z,this.seed+604)*8)}];}
 chunk(cx,cz) {cx=Math.floor(cx);cz=Math.floor(cz);const key=cx+','+cz;let c=this._chunks.get(key);if(c){this._chunks.delete(key);this._chunks.set(key,c);c.used=++this._clock;return c;}c=this._generate(cx,cz);this._chunks.set(key,c);while(this._chunks.size>this.maxCachedChunks)this._chunks.delete(this._chunks.keys().next().value);return c;}
 voxel(x,y,z) {x=Math.floor(x);y=Math.floor(y);z=Math.floor(z);if(y<WORLD_MIN_Y||y>=WORLD_MAX_Y||!Number.isFinite(x)||!Number.isFinite(z))return BLOCKS.AIR;const cx=Math.floor(x/16),cz=Math.floor(z/16),c=this.chunk(cx,cz);return c.data[wvIndex(x-cx*16,y,z-cz*16)];}
 baseVoxel(x,y,z) {x=Math.floor(x);y=Math.floor(y);z=Math.floor(z);if(y<WORLD_MIN_Y||y>=WORLD_MAX_Y||!Number.isFinite(x)||!Number.isFinite(z))return BLOCKS.AIR;const cx=Math.floor(x/16),cz=Math.floor(z/16),c=this.chunk(cx,cz);return c.baseData[wvIndex(x-cx*16,y,z-cz*16)];}
 set(x,y,z,type) {if(![x,y,z,type].every(Number.isInteger)||y<=WORLD_MIN_Y||y>=WORLD_MAX_Y||type<0||type>48||!Number.isSafeInteger(x)||!Number.isSafeInteger(z))return false;const old=this.voxel(x,y,z);if(old===BLOCKS.BEDROCK||old===type)return false;const key=x+','+y+','+z,base=this.baseVoxel(x,y,z),cx=Math.floor(x/16),cz=Math.floor(z/16),chunkKey=cx+','+cz;let bucket=this._editsByChunk.get(chunkKey);if(type===base){this.edits.delete(key);bucket?.delete(key);if(bucket?.size===0)this._editsByChunk.delete(chunkKey);}else{this.edits.set(key,type);if(!bucket){bucket=new Map();this._editsByChunk.set(chunkKey,bucket);}bucket.set(key,type);}const c=this.chunk(cx,cz);c.data[wvIndex(x-cx*16,y,z-cz*16)]=type;return true;}
 setEdits(entries) {const incoming=Array.from(entries);this.edits.clear();this._editsByChunk.clear();for(const [key,type]of incoming){this.edits.set(key,type);const p=key.split(',').map(Number),chunkKey=Math.floor(p[0]/16)+','+Math.floor(p[2]/16);let bucket=this._editsByChunk.get(chunkKey);if(!bucket){bucket=new Map();this._editsByChunk.set(chunkKey,bucket);}bucket.set(key,type);}this._chunks.clear();}
 isCave(x,y,z) {x=Math.floor(x);y=Math.floor(y);z=Math.floor(z);if(y<WORLD_MIN_Y||y>=WORLD_MAX_Y)return false;const cx=Math.floor(x/16),cz=Math.floor(z/16),c=this.chunk(cx,cz);return !!c.cave[wvIndex(x-cx*16,y,z-cz*16)];}
 evictExcept(keys) {for(const key of this._chunks.keys())if(!keys.has(key))this._chunks.delete(key);}
 stats() {return {seed:this.seed,residentChunks:this._chunks.size,residentRegions:this._regions.size,generatedChunks:this._generated,edits:this.edits.size,minY:WORLD_MIN_Y,maxY:WORLD_MAX_Y,chunkSize:16,regionSize:64,maxCachedChunks:this.maxCachedChunks};}
}
