const assert=require('node:assert/strict');const{chromium}=require('playwright');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox','--enable-unsafe-swiftshader']});try{
 const errors=[],rooms=new Map();const installTransport=require('./friend-transport.cjs');async function page(){const p=await browser.newPage({viewport:{width:1100,height:780}});p.on('pageerror',e=>{errors.push(e.message);console.log('BROWSER ERROR',e.message)});p.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text())});await installTransport(p,rooms);await p.addInitScript(()=>{Object.defineProperty(window,'devicePixelRatio',{value:.18});HTMLElement.prototype.requestPointerLock=()=>Promise.resolve();});await p.goto('http://127.0.0.1:8000');await p.waitForFunction(()=>window.blockCoaster);return p;}
 const host=await page(),guest=await page(),state=p=>p.evaluate(()=>blockCoaster.getState());await host.click('#enter');await guest.click('#enter');
 const floor=[];for(let x=20;x<46;x++)for(let z=20;z<46;z++)floor.push([`${x},95,${z}`,11]);
 async function fixture(p){const s=await state(p);Object.assign(s,{edits:[...floor,['32,97,30',2],['36,96,32',18]],player:[.5,96,.5],view:[0,0],worldTime:100,rails:[],bag:Array(36).fill(null),chests:{},furnaceJobs:[],furnaceFuel:{}});s.bag[0]={id:'diamondPick',count:1,durability:900};s.bag[1]={id:'plank',count:12};s.bag[2]={id:'rail',count:12};await p.evaluate(s=>localStorage.setItem('block-coaster-world-v6',JSON.stringify(s)),s);await p.click('#load');}
 await fixture(host);await fixture(guest);await host.click('#friendsToggle');await host.fill('#friendName','招待する人');await host.click('#createInvite');await host.waitForFunction(()=>document.querySelector('#friendOutput').value.includes('#friend='),null,{timeout:20000});const invite=await host.inputValue('#friendOutput');assert(invite.includes('BC1.'));const offerData=JSON.parse(Buffer.from(new URLSearchParams(new URL(invite).hash.slice(1)).get('friend').slice(4),'base64').toString());
 await guest.click('#friendsToggle');await guest.fill('#friendName','友達');await guest.fill('#friendInput',invite);await guest.click('#joinFriend');await guest.waitForFunction(()=>document.querySelector('#friendOutput').value.startsWith('BC1.'),null,{timeout:20000});const answer=await guest.inputValue('#friendOutput');const answerData=JSON.parse(Buffer.from(answer.slice(4),'base64').toString());await host.fill('#friendInput',answer);await host.click('#acceptFriend');try{await host.waitForFunction(()=>blockCoaster.friendState().connected,null,{timeout:20000});}catch(e){console.log('HOST',await host.evaluate(()=>blockCoaster.friendState()),await host.locator('#friendsStatus').innerText());console.log('GUEST',await guest.evaluate(()=>blockCoaster.friendState()),await guest.locator('#friendsStatus').innerText());throw e;}await guest.waitForFunction(()=>blockCoaster.friendState().ready,null,{timeout:20000});await host.click('#closeFriends');
 await host.waitForFunction(()=>blockCoaster.friendState().avatar.visible);await guest.waitForFunction(()=>blockCoaster.friendState().avatar.visible);assert.equal((await host.evaluate(()=>blockCoaster.friendState())).avatar.name,'友達');assert.equal((await guest.evaluate(()=>blockCoaster.friendState())).avatar.name,'招待する人');assert.equal(await guest.evaluate(()=>blockCoaster.voxel(32,97,30)),2);console.log('PASS simulated transport: shipped invitation, answer, initial terrain and named avatars');
 // The invite creates a separate guest position. Look at the same target from there.
 async function look(p,x,y,z){const s=await state(p),dx=x-32-s.position[0],dy=y-s.position[1],dz=z-32-s.position[2],yaw=Math.atan2(-dx,-dz),pitch=Math.atan2(dy,Math.hypot(dx,dz));await p.mouse.move(550,390);await p.mouse.down();await p.dispatchEvent('#world canvas','mousemove',{movementX:(s.yaw-yaw)/.0025,movementY:(s.pitch-pitch)/.0025,bubbles:true});await p.mouse.up();await p.waitForTimeout(150);}
 await look(guest,32.5,97.5,30.5);await guest.keyboard.press('KeyE');await host.waitForFunction(()=>blockCoaster.voxel(32,97,30)===0,null,{timeout:15000});await guest.waitForFunction(()=>!blockCoaster.friendState().pending);assert.equal((await state(guest)).bag.find(v=>v?.id==='stone').count,1);assert(!(await state(host)).bag.some(v=>v?.id==='stone'));console.log('PASS guest mining shares terrain and awards only the guest');
 await guest.keyboard.press('Digit2');await look(guest,33.5,95.99,31.5);await guest.keyboard.press('KeyE');await guest.waitForFunction(()=>!blockCoaster.friendState().pending);await host.waitForFunction(()=>blockCoaster.voxel(33,96,31)===10);assert.equal((await state(guest)).bag.find(v=>v?.id==='plank').count,11);console.log('PASS guest building shares placed block and spends own material');
 await guest.keyboard.press('Digit1');await look(guest,33.5,96.5,31.5);const guestBefore=await state(guest);await guest.evaluate(()=>{const ch=window.__testRtcPeer.channel;window.__heldPackets=[];window.__originalSend=ch.send.bind(ch);ch.send=data=>window.__heldPackets.push(data);});await guest.keyboard.press('KeyE');await guest.waitForFunction(()=>blockCoaster.friendState().pending,null,{timeout:15000});await look(host,33.5,96.5,31.5);await host.keyboard.press('KeyE');await host.waitForFunction(()=>blockCoaster.voxel(33,96,31)===0,null,{timeout:15000});await guest.evaluate(()=>{const ch=window.__testRtcPeer.channel;ch.send=window.__originalSend;for(const frame of window.__heldPackets)ch.send(frame);});await guest.waitForFunction(()=>!blockCoaster.friendState().pending);assert.deepEqual((await state(guest)).bag,guestBefore.bag);assert.equal((await state(host)).bag.find(v=>v?.id==='plank').count,13);assert.equal(await guest.evaluate(()=>blockCoaster.voxel(33,96,31)),0);assert((await guest.evaluate(()=>blockCoaster.experienceStats())).emitted>=24);console.log('PASS conflicting simultaneous mining rolls back guest inventory and durability; bounded particles emitted');
 await host.keyboard.down('KeyS');await host.waitForTimeout(500);await host.keyboard.up('KeyS');const hp=(await state(host)).player;await guest.waitForFunction(p=>Math.hypot(blockCoaster.friendState().avatar.position[0]-p[0],blockCoaster.friendState().avatar.position[2]-p[2])<.1,hp);console.log('PASS remote movement updates avatar');
 await guest.click('#friendsToggle');await guest.fill('#friendChatInput','いっしょに家をつくろう！');await guest.click('#friendChatForm button');await host.click('#friendsToggle');await host.waitForFunction(()=>document.querySelector('#friendChatLog').textContent.includes('いっしょに家をつくろう！'));await host.screenshot({path:'/tmp/friends-connected.png'});await host.click('#closeFriends');await guest.click('#closeFriends');console.log('PASS player chat over the connected data channel');
 await look(guest,36.5,96.5,32.5);await guest.keyboard.press('KeyF');await guest.waitForFunction(()=>!blockCoaster.friendState().pending);assert.match(await guest.locator('#inventoryTitle').innerText(),/チェスト/);await guest.keyboard.down('Shift');await guest.locator('#bag [data-slot="1"]').click();await guest.keyboard.up('Shift');await guest.waitForFunction(()=>!blockCoaster.friendState().pending);await host.waitForFunction(()=>Object.values(blockCoaster.getState().chests).some(slots=>slots.some(s=>s?.id==='plank'&&s.count===11)));await guest.keyboard.press('Escape');console.log('PASS guest chest deposits share contents without duplicating inventory');
 await guest.keyboard.press('Digit3');for(const z of[30,29]){await look(guest,34.5,95.99,z+.5);await guest.keyboard.press('KeyE');await guest.waitForFunction(()=>!blockCoaster.friendState().pending);await host.waitForFunction(n=>blockCoaster.getState().rails.length===n,31-z);}assert.equal((await state(guest)).bag.find(v=>v?.id==='rail').count,10);assert.equal((await state(host)).bag.find(v=>v?.id==='rail').count,12);await host.click('#ride');await host.waitForTimeout(600);assert.equal((await state(host)).mode,'ride');await host.click('#ride');console.log('PASS guest rails are shared and host can ride the new route');
 await host.click('#save');await guest.click('#save');assert((await host.evaluate(()=>JSON.parse(localStorage.getItem('block-coaster-world-v6')))).chests['36,96,32'].some(Boolean));await guest.click('#friendsToggle');await guest.click('#disconnectFriend');await host.waitForFunction(()=>!blockCoaster.friendState().connected);await guest.waitForFunction(()=>!blockCoaster.friendState().avatar.visible);console.log('PASS both players save shared construction and disconnect cleans avatars');assert.deepEqual(errors,[]);console.log('PASS no browser errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
