import assert from 'node:assert/strict';
import {NightCreatures,nightAt,daylightAt} from '../monsters.js';
import {miningProfile} from '../mining.js';
import {BLOCKS as B} from '../world.js';
import {itemDefs} from '../items.js';
const check=(name,fn)=>{fn();console.log('PASS '+name);};
function simulation(extra={}){const events={hurt:0,spawn:0,removed:0,killed:0};const env={random:()=>.1,ground:()=>0,occupy:()=>true,safeFloor:()=>true,light:()=>null,sky:()=>true,visible:()=>true,spawn:()=>events.spawn++,remove:()=>events.removed++,hurt:()=>events.hurt++,defeated:()=>events.killed++,...extra};return {m:new NightCreatures(env),events};}
const hero={x:0,y:0,z:0},context={enabled:true,night:true,player:hero};
check('Clock and daylight agree across midnight and a complete day',()=>{assert.equal(nightAt(0),false);assert.equal(nightAt(299.9),false);assert.equal(nightAt(300),true);assert.equal(nightAt(599.9),true);assert.equal(nightAt(600),false);assert(daylightAt(150)>daylightAt(450)*10);});
check('Every mineable stone and ore can be harvested by hand, stronger tools reduce time',()=>{for(const type of[B.STONE,B.IRON,B.GOLD,B.DIAMOND,B.EMERALD,B.OBSIDIAN]){const hand=miningProfile(type),wood=miningProfile(type,itemDefs.woodPick),iron=miningProfile(type,itemDefs.ironPick),diamond=miningProfile(type,itemDefs.diamondPick);assert(hand.harvest);assert(hand.time>wood.time&&wood.time>iron.time&&iron.time>diamond.time);}assert(miningProfile(B.WOOD,itemDefs.ironAxe).time<miningProfile(B.WOOD,itemDefs.ironPick).time);});
check('Day does not spawn creatures; darkness does; light blocks all spawn attempts',()=>{const {m}=simulation();m.tick(1,{...context,night:false});assert.equal(m.creatures.length,0);m.tick(1,context);assert.equal(m.creatures.length,1);const safe=simulation({light:(x,y,z)=>({x,y,z})}).m;safe.tick(1,context);assert.equal(safe.creatures.length,0);assert.equal(safe.stats.blockedByLight,12);});
check('Creatures chase, respect collisions, attack with cooldown, and spare a torch-lit player',()=>{const {m,events}=simulation();m.spawn(hero);const c=m.creatures[0];c.x=5;c.z=0;const before=c.x;for(let i=0;i<20;i++)m.tick(.05,context);assert(c.x<before);m.env.occupy=()=>false;const blocked=c.x;for(let i=0;i<20;i++)m.tick(.05,context);assert.equal(c.x,blocked);m.env.occupy=()=>true;c.x=1;c.z=0;c.think=0;m.tick(.05,context);assert.equal(events.hurt,1);for(let i=0;i<10;i++)m.tick(.05,context);assert.equal(events.hurt,1);m.env.light=()=>({x:0,y:.8,z:0});for(let i=0;i<40;i++)m.tick(.05,context);assert.equal(events.hurt,1);assert(c.x>1);});
check('Melee has range/occlusion/cooldown and death removes visuals; sunrise burns survivors',()=>{const {m,events}=simulation();m.spawn(hero);const c=m.creatures[0];c.x=0;c.z=-2;const origin={x:0,y:1,z:0},direction={x:0,y:0,z:-1};assert.equal(m.aimed(origin,direction),c);assert.equal(m.aimed(origin,direction,1),null);assert.equal(m.aimed({...origin,z:5},direction),null);m.strike(c,7);const hp=c.hp;m.strike(c,7);assert.equal(c.hp,hp);m.tick(.4,{...context,invulnerable:true});m.strike(c,30);assert.equal(events.killed,1);assert.equal(events.removed,1);m.spawn(hero);for(let i=0;i<120;i++)m.tick(.05,{...context,night:false});assert.equal(m.creatures.length,0);assert.equal(events.spawn,2);assert.equal(events.removed,2);});
check('Creature population remains bounded and distant actors are disposed',()=>{let r=0;const {m,events}=simulation({random:()=>((r++*0.161)%1)});for(let i=0;i<300;i++)m.tick(.1,{...context,invulnerable:true});assert(m.creatures.length<=6);m.tick(.1,{...context,player:{x:1000,y:0,z:1000},night:false});assert.equal(m.creatures.length,0);assert.equal(events.spawn,events.removed);});
