const assert=require('node:assert/strict');const{chromium}=require('playwright');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});try{const p=await b.newPage({viewport:{width:1200,height:800}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(()=>{HTMLElement.prototype.requestPointerLock=()=>Promise.resolve();Object.defineProperty(window,'devicePixelRatio',{value:.18});});await p.goto(process.env.GAME_URL||'http://127.0.0.1:8000');await p.waitForFunction(()=>window.blockCoaster);await p.locator('#enter').click();await p.locator('#distance').selectOption('3');
const state=()=>p.evaluate(()=>blockCoaster.getState());const count=async k=>(await state()).bag.reduce((a,s)=>a+(s?.id===k?s.count:0),0);
async function fixture(edit){let s=await state();delete s.heights;edit(s);await p.evaluate(s=>localStorage.setItem('block-coaster-world-v6',JSON.stringify(s)),s);await p.locator('#load').click();await p.waitForTimeout(100);assert(!/壊れて/.test(await p.locator('#message').innerText()));}
async function look(x,y,z){const s=await state(),o=s.position;const dx=x-32-o[0],dy=y-o[1],dz=z-32-o[2];const yaw=Math.atan2(-dx,-dz),pitch=Math.atan2(dy,Math.hypot(dx,dz));await p.mouse.move(600,400);await p.mouse.down();await p.dispatchEvent('canvas','mousemove',{movementX:(s.yaw-yaw)/.0025,movementY:(s.pitch-pitch)/.0025,bubbles:true});await p.mouse.up();await p.waitForTimeout(80);}
async function teleport(x,y,z){await fixture(s=>{s.player=[x-32,y,z-32];});}
async function select(key){const s=await state();const i=key?s.bag.findIndex(v=>v?.id===key):s.bag.findIndex(v=>!v);assert(i>=0&&i<9,`hotbar ${key} ${i}`);await p.keyboard.press('Digit'+(i+1));}
async function mine(x,y,z,key){await select(key);const o=(await state()).position;await look(x+(o[0]+32<x?.01:o[0]+32>x+1?.99:.5),y+.45,z+(o[2]+32<z?.01:o[2]+32>z+1?.99:.5));let s=await state();assert(s.target&&s.target.x===x&&s.target.y===y&&s.target.z===z,`target ${JSON.stringify(s.target)} vs ${x},${y},${z}`);const old=await p.evaluate(([x,y,z])=>blockCoaster.voxel(x,y,z),[x,y,z]);await p.keyboard.press('KeyE');await p.waitForFunction(([x,y,z,old])=>blockCoaster.voxel(x,y,z)!==old,[x,y,z,old],{timeout:15000});}
async function recipe(k){await p.locator(`[data-recipe="${k}"]`).click();assert(!(await p.locator('#craftOutput').isDisabled()),`recipe ${k}: ${await p.locator('#message').innerText()}`);await p.locator('#craftOutput').click();}
// Gather logs through real mining, with only navigation positions moved for the test.
const heights=(await state()).heights;for(const [x,z]of[[29,13],[36,10],[19,9]]){const h=heights[z*64+x];await teleport(x-.5,h,z+.5);for(let y=h;y<h+(x===19?1:2);y++)await mine(x,y,z,null);}assert.equal(await count('log'),5);console.log('PASS harvested 5 logs');
await p.keyboard.press('KeyI');for(let i=0;i<5;i++)await recipe('plank');await recipe('stick');await recipe('stick');await recipe('table');assert.equal(await p.locator('[data-recipe="woodPick"]').count(),0,'3x3 tools remain absent from hand crafting');assert.equal(await p.locator('[data-recipe="rail"]').count(),0,'unaffordable recipes remain absent');assert.equal(await count('plank'),12);assert.equal(await count('stick'),8);await p.keyboard.press('Escape');
// Place a workbench and open it; a 2x2 recipe cannot produce a pickaxe.
await teleport(31.5,heights[10*64+31],10.5);await select('table');await look(32.5,heights[10*64+32]-.5,10.5);console.log('Table target',(await state()).target);await p.keyboard.press('KeyE');assert.equal(await count('table'),0);await p.keyboard.press('KeyF');assert.match(await p.locator('#inventoryTitle').innerText(),/3 × 3/);await recipe('woodPick');await p.keyboard.press('Escape');console.log('PASS crafted and placed table + wooden pick');
// Mine an accessible stone cliff by scanning for a solid with a clear standing position.
async function findBlock(type){return p.evaluate(type=>{const{size,minY,maxY}=blockCoaster.dimensions();for(let y=-8;y<30;y++)for(let z=3;z<size-3;z++)for(let x=3;x<size-3;x++)if(blockCoaster.voxel(x,y,z)===type)for(const [dx,dz]of[[1,0],[-1,0],[0,1],[0,-1]]){const a=x+dx,c=z+dz;if(blockCoaster.voxel(a,y,c)===0&&blockCoaster.voxel(a,y+1,c)===0&&![0,22,23,38,47].includes(blockCoaster.voxel(a,y-1,c)))return {x,y,z,px:a+.5,pz:c+.5};}throw Error('No exposed type '+type);},type);}
for(let i=0;i<11;i++){const t=await findBlock(2);await teleport(t.px,t.y,t.pz);await mine(t.x,t.y,t.z,'woodPick');}assert.equal(await count('stone'),11);assert((await state()).bag.find(s=>s?.id==='woodPick').durability<60);console.log('PASS 11 cobblestone + durability');
// Use the placed table again to craft stone tools and a furnace.
let table=(await state()).edits.find(([,t])=>t===16)[0];const decode=key=>{const [x,y,z]=key.split(',').map(Number);return{x,y,z};};const tc=decode(table);await teleport(tc.x-.5,tc.y,tc.z+.5);await look(tc.x+.5,tc.y+.5,tc.z+.5);await p.keyboard.press('KeyF');await recipe('stonePick');await recipe('furnace');await p.keyboard.press('Escape');assert.equal(await count('stone'),0);console.log('PASS stone pick and furnace');
for(let i=0;i<2;i++){const t=await findBlock(12);await teleport(t.px,t.y,t.pz);await mine(t.x,t.y,t.z,'stonePick');}for(let i=0;i<6;i++){const t=await findBlock(13);await teleport(t.px,t.y,t.pz);await mine(t.x,t.y,t.z,'stonePick');}assert.equal(await count('ironOre'),6);console.log('PASS coal + 6 iron ore');
await teleport(tc.x-.5,tc.y,tc.z+.5);await select('furnace');await look(tc.x-1.5,tc.y-.5,tc.z+.5);await p.keyboard.press('KeyE');assert.equal(await count('furnace'),0);const fi=decode((await state()).edits.find(([,t])=>t===17)[0]);await look(fi.x+.5,fi.y+.5,fi.z+.5);await p.keyboard.press('KeyF');assert.match(await p.locator('#inventoryTitle').innerText(),/かまど/);for(let i=0;i<6;i++)await p.locator('#smeltRecipes button').filter({hasText:'鉄の原石'}).click();await p.waitForFunction(()=>blockCoaster.getState().bag.some(s=>s?.id==='iron'&&s.count===6),null,{timeout:120000});await p.keyboard.press('Escape');console.log('PASS smelted 6 iron');
await look(tc.x+.5,tc.y+.5,tc.z+.5);await p.keyboard.press('KeyF');await recipe('rail');await p.keyboard.press('Escape');assert.equal(await count('rail'),16);console.log('PASS 16 crafted rails');
// Rail cost, undo refunds, one-person ride.
await teleport(32.5,heights[8*64+32],8.5);await select('rail');await look(32.5,heights[8*64+32]-.5,8.5);await p.keyboard.press('KeyE');assert.equal(await count('rail'),15);await look(32.5,heights[9*64+32]-.5,9.5);await p.keyboard.press('KeyE');assert.equal((await state()).rails.length,2);await p.locator('#ride').click();await p.waitForTimeout(500);assert.equal((await state()).mode,'ride');await p.locator('#ride').click();await p.keyboard.press('KeyQ');assert.equal(await count('rail'),15);console.log('PASS placed rails, ride, refund');
await p.locator('#save').click();const saved=await state();await p.reload();await p.waitForFunction(()=>window.blockCoaster);await p.locator('#enter').click();await p.locator('#load').click();assert.deepEqual((await state()).bag,saved.bag);assert.deepEqual((await state()).rails,saved.rails);assert.equal(errors.length,0,errors.join('\n'));console.log('PASS save/reload, no JS errors');await p.screenshot({path:'/tmp/craft-progression.png'});
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
